version: 2
build:
  os: ubuntu-20.04
  tools:
    python: mambaforge-4.10
  jobs:
    pre_build:
      - doit setup
      - doit examples
      - doit lite
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
conda:
  environment: .binder/environment.yml
